<?php

use Detain\MyAdminPleskAutomation\PPAConnector;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-26 at 08:04:10.
 */
class PPAConnectorTest extends TestCase
{
	/**
	 * @var PPAConnector
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new PPAConnector;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}

	/**
	 * @covers Detain\MyAdminPleskAutomation\PPAConnector::getInstance
	 * @todo   Implement testGetInstance().
	 */
	public function testGetInstance()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers Detain\MyAdminPleskAutomation\PPAConnector::checkResponse
	 * @todo   Implement testCheckResponse().
	 */
	public function testCheckResponse()
	{
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
			'This test has not been implemented yet.'
		);
	}
}
